models:
  # can be tf_idf, bert, roberta, distilbert
  control: models/catboost_model_distilbert
  control_posts_features: distilbert
  test: models/catboost_model_distilbert
  test_posts_features: distilbert

user_salt: my_awesome_salt
return_posts_number: 1
