#pg_connection: postgresql://robot-startml-ro:pheiph0hahj1Vaif@postgres.lab.karpov.courses:6432/startml
pg_connection:
local_data_storage: ../data
random_state: 10101
# can be tf_idf, bert, roberta, distilbert
text_embeddings: tf_idf
n_pca_components: 20
n_kmeans_clusters: 15

training_params:
  train_size: 0.8
  metric: roc_auc_score
  select_hp: True
  object_cols:
    [
      "topic",
      "text_cluster",
      "gender",
      "country",
      "city",
      "exp_group",
      "hour",
      "month",
      "os",
      "source",
    ]
  default_catboost_params:
    iterations: 5
    learning_rate: 1
    depth: 2
  optuna_search:
    n_trials: 3
    search_params:
      objective: ["Logloss", "CrossEntropy"]
      colsample_bylevel: [0.01, 0.1]
      depth: [1, 12]
      boosting_type: ["Ordered", "Plain"]
      bootstrap_type: ["Bayesian", "Bernoulli", "MVS"]
      bagging_temperature: [0, 10]
      subsample: [0.1, 1]

  retrain_whole_dataset: True
